set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(GNU_MACHINE riscv64-unknown-linux-gnu CACHE STRING "GNU compiler triple")

# include("${CMAKE_CURRENT_LIST_DIR}/flags-riscv64.cmake")
function(ocv_set_platform_flags_gcc VAR)
  if(ENABLE_RVV OR RISCV_RVV_SCALABLE)
    set(flags "-march=rv64gcv_zba_zbb_zbc_zbs")
  else()
    set(flags "-march=rv64gc_zba_zbb_zbc_zbs")
  endif()
  set(${VAR} "${flags}" PARENT_SCOPE)
endfunction()

if(COMMAND ocv_set_platform_flags_gcc)
ocv_set_platform_flags_gcc(CMAKE_CXX_FLAGS_INIT)
ocv_set_platform_flags_gcc(CMAKE_C_FLAGS_INIT)
endif()
set(CMAKE_CXX_FLAGS_INIT "-mcpu=spacemit-x60 ${CMAKE_CXX_FLAGS_INIT}")
set(CMAKE_C_FLAGS_INIT "-mcpu=spacemit-x60 ${CMAKE_C_FLAGS_INIT}")

include("${CMAKE_CURRENT_LIST_DIR}/riscv-gnu.toolchain.cmake")
