# This is a basic workflow to help you get started with Actions

name: tests_on_boards

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-gcc-arm64-timvx-khadas:
    # The type of runner that the job will run on
    runs-on: [self-hosted, khadas-vim3]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: configure
        run: mkdir build && cd build && cmake -DWITH_TIMVX=ON -DWITH_OPENCL=OFF ..
      - name: build
        run: cmake --build build --target opencv_test_dnn -j 4 --
      - name: tests for int8 layers
        run: |
          cd build
          OPENCV_TEST_DATA_PATH=/home/opencv-cn/Workspace/opencv/opencv_extra/testdata ./bin/opencv_test_dnn --gtest_filter="Test_Int8_layers.*/1"
      - name: tests for models
        run: echo 'TBD'
